package com.tiendas3b.ticketdoctor.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMP_CAUSE".
 */
public class ImpCause {

    private Long id;
    /** Not-null value. */
    private String description;
    /** Not-null value. */
    private String generalDescription;
    /** Not-null value. */
    private String impSolution;
    private String code;
    private short status;

    public ImpCause() {
    }

    public ImpCause(Long id) {
        this.id = id;
    }

    public ImpCause(Long id, String description, String generalDescription, String impSolution, String code, short status) {
        this.id = id;
        this.description = description;
        this.generalDescription = generalDescription;
        this.impSolution = impSolution;
        this.code = code;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDescription() {
        return description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String description) {
        this.description = description;
    }

    /** Not-null value. */
    public String getGeneralDescription() {
        return generalDescription;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGeneralDescription(String generalDescription) {
        this.generalDescription = generalDescription;
    }

    /** Not-null value. */
    public String getImpSolution() {
        return impSolution;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImpSolution(String impSolution) {
        this.impSolution = impSolution;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public short getStatus() {
        return status;
    }

    public void setStatus(short status) {
        this.status = status;
    }

}
