package com.tiendas3b.ticketdoctor.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROVIDER".
 */
public class Provider {

    private Long id;
    /** Not-null value. */
    private String businessName;
    private String description;
    private boolean rfc;
    private String street;
    private String number;
    private String neighborhood;
    private String township;
    private boolean city;
    private String postalCode;
    private String phone1;
    private String extension1;
    private String phone2;
    private String extension2;
    private Boolean cont1;
    private Boolean phoneCont1;
    private String emailCont1;
    private String cont2;
    private String phoneCont2;
    private String emailCont2;
    private boolean account;
    private String deliveryDays;
    private String payDays;
    private String status;
    private String key;

    public Provider() {
    }

    public Provider(Long id) {
        this.id = id;
    }

    public Provider(Long id, String businessName, String description, boolean rfc, String street, String number, String neighborhood, String township, boolean city, String postalCode, String phone1, String extension1, String phone2, String extension2, Boolean cont1, Boolean phoneCont1, String emailCont1, String cont2, String phoneCont2, String emailCont2, boolean account, String deliveryDays, String payDays, String status, String key) {
        this.id = id;
        this.businessName = businessName;
        this.description = description;
        this.rfc = rfc;
        this.street = street;
        this.number = number;
        this.neighborhood = neighborhood;
        this.township = township;
        this.city = city;
        this.postalCode = postalCode;
        this.phone1 = phone1;
        this.extension1 = extension1;
        this.phone2 = phone2;
        this.extension2 = extension2;
        this.cont1 = cont1;
        this.phoneCont1 = phoneCont1;
        this.emailCont1 = emailCont1;
        this.cont2 = cont2;
        this.phoneCont2 = phoneCont2;
        this.emailCont2 = emailCont2;
        this.account = account;
        this.deliveryDays = deliveryDays;
        this.payDays = payDays;
        this.status = status;
        this.key = key;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBusinessName() {
        return businessName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean getRfc() {
        return rfc;
    }

    public void setRfc(boolean rfc) {
        this.rfc = rfc;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getNeighborhood() {
        return neighborhood;
    }

    public void setNeighborhood(String neighborhood) {
        this.neighborhood = neighborhood;
    }

    public String getTownship() {
        return township;
    }

    public void setTownship(String township) {
        this.township = township;
    }

    public boolean getCity() {
        return city;
    }

    public void setCity(boolean city) {
        this.city = city;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getPhone1() {
        return phone1;
    }

    public void setPhone1(String phone1) {
        this.phone1 = phone1;
    }

    public String getExtension1() {
        return extension1;
    }

    public void setExtension1(String extension1) {
        this.extension1 = extension1;
    }

    public String getPhone2() {
        return phone2;
    }

    public void setPhone2(String phone2) {
        this.phone2 = phone2;
    }

    public String getExtension2() {
        return extension2;
    }

    public void setExtension2(String extension2) {
        this.extension2 = extension2;
    }

    public Boolean getCont1() {
        return cont1;
    }

    public void setCont1(Boolean cont1) {
        this.cont1 = cont1;
    }

    public Boolean getPhoneCont1() {
        return phoneCont1;
    }

    public void setPhoneCont1(Boolean phoneCont1) {
        this.phoneCont1 = phoneCont1;
    }

    public String getEmailCont1() {
        return emailCont1;
    }

    public void setEmailCont1(String emailCont1) {
        this.emailCont1 = emailCont1;
    }

    public String getCont2() {
        return cont2;
    }

    public void setCont2(String cont2) {
        this.cont2 = cont2;
    }

    public String getPhoneCont2() {
        return phoneCont2;
    }

    public void setPhoneCont2(String phoneCont2) {
        this.phoneCont2 = phoneCont2;
    }

    public String getEmailCont2() {
        return emailCont2;
    }

    public void setEmailCont2(String emailCont2) {
        this.emailCont2 = emailCont2;
    }

    public boolean getAccount() {
        return account;
    }

    public void setAccount(boolean account) {
        this.account = account;
    }

    public String getDeliveryDays() {
        return deliveryDays;
    }

    public void setDeliveryDays(String deliveryDays) {
        this.deliveryDays = deliveryDays;
    }

    public String getPayDays() {
        return payDays;
    }

    public void setPayDays(String payDays) {
        this.payDays = payDays;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

}
