package com.tiendas3b.ticketdoctor.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYMPTOM".
 */
public class Symptom {

    private Long id;
    /** Not-null value. */
    private String name;
    private String sub;
    private String description;
    private short failure;
    /** Not-null value. */
    private String status;

    public Symptom() {
    }

    public Symptom(Long id) {
        this.id = id;
    }

    public Symptom(Long id, String name, String sub, String description, short failure, String status) {
        this.id = id;
        this.name = name;
        this.sub = sub;
        this.description = description;
        this.failure = failure;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getSub() {
        return sub;
    }

    public void setSub(String sub) {
        this.sub = sub;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public short getFailure() {
        return failure;
    }

    public void setFailure(short failure) {
        this.failure = failure;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

}
