package com.tiendas3b.ticketdoctor.db.dao;

import com.tiendas3b.ticketdoctor.db.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYMPTOM_DIAGNOSTIC".
 */
public class SymptomDiagnostic {

    private Long id;
    private boolean sub;
    private boolean status;
    /** Not-null value. */
    private String renew;
    private long diagnosticId;
    private long symptomId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient SymptomDiagnosticDao myDao;

    private Diagnostic diagnostic;
    private Long diagnostic__resolvedKey;

    private Symptom symptom;
    private Long symptom__resolvedKey;


    public SymptomDiagnostic() {
    }

    public SymptomDiagnostic(Long id) {
        this.id = id;
    }

    public SymptomDiagnostic(Long id, boolean sub, boolean status, String renew, long diagnosticId, long symptomId) {
        this.id = id;
        this.sub = sub;
        this.status = status;
        this.renew = renew;
        this.diagnosticId = diagnosticId;
        this.symptomId = symptomId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getSymptomDiagnosticDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public boolean getSub() {
        return sub;
    }

    public void setSub(boolean sub) {
        this.sub = sub;
    }

    public boolean getStatus() {
        return status;
    }

    public void setStatus(boolean status) {
        this.status = status;
    }

    /** Not-null value. */
    public String getRenew() {
        return renew;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRenew(String renew) {
        this.renew = renew;
    }

    public long getDiagnosticId() {
        return diagnosticId;
    }

    public void setDiagnosticId(long diagnosticId) {
        this.diagnosticId = diagnosticId;
    }

    public long getSymptomId() {
        return symptomId;
    }

    public void setSymptomId(long symptomId) {
        this.symptomId = symptomId;
    }

    /** To-one relationship, resolved on first access. */
    public Diagnostic getDiagnostic() {
        long __key = this.diagnosticId;
        if (diagnostic__resolvedKey == null || !diagnostic__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            DiagnosticDao targetDao = daoSession.getDiagnosticDao();
            Diagnostic diagnosticNew = targetDao.load(__key);
            synchronized (this) {
                diagnostic = diagnosticNew;
            	diagnostic__resolvedKey = __key;
            }
        }
        return diagnostic;
    }

    public void setDiagnostic(Diagnostic diagnostic) {
        if (diagnostic == null) {
            throw new DaoException("To-one property 'diagnosticId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.diagnostic = diagnostic;
            diagnosticId = diagnostic.getId();
            diagnostic__resolvedKey = diagnosticId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Symptom getSymptom() {
        long __key = this.symptomId;
        if (symptom__resolvedKey == null || !symptom__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            SymptomDao targetDao = daoSession.getSymptomDao();
            Symptom symptomNew = targetDao.load(__key);
            synchronized (this) {
                symptom = symptomNew;
            	symptom__resolvedKey = __key;
            }
        }
        return symptom;
    }

    public void setSymptom(Symptom symptom) {
        if (symptom == null) {
            throw new DaoException("To-one property 'symptomId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.symptom = symptom;
            symptomId = symptom.getId();
            symptom__resolvedKey = symptomId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
